recommendations:
  NumOfProducts:
    conditions:
      - value: 1
        messages:
          - "Предложить второй продукт (кредитная карта, сберегательный счет)"
          - "Специальные условия для первой кросс-продажы"
          - "Выгодные скидки, персональная программа кэшбэка"

  IsActiveMember:
    conditions:
      - value: 0
        messages:
          - "Серия с электронными письмами с эксклюзивными предложениями"
          - "Персональный звонок от менеджера по работе с клиентами"
          - "Бонус за первую активность после перерыва"

  Age:
    conditions:
      - value: ">45"
        messages:
          - "Специальная программа для клиентов 45+"
          - "Консультация по пенсионным накоплениям"
          - "Персональный финансовый обзор"

  probability:
    conditions:
      - value: ">0.7"
        messages:
          - "Высокий приоритет: Назначить персонального менеджера"

  default:
    messages:
      - "Стандартная программа лояльности"
